sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
before_install: npm install -g grunt-cli
install: npm install
  